### ISSUE TITLE
Documentation of README

### ISSUE THREAD

**Issue by JAYAPRAKASHJAISANKAR** [fssa-batch3/jayaprakash.jaisankar__corejava_project_2#12]
### Description:
This issue involves documenting the README file for the project. The README will provide essential information about the project setup, software requirements, modules, validations, testing, and future improvements.

### Tasks :
 - [ ] Introduction
 - [ ] Purpose
 - [ ] Features
 - [ ] User Persona
 - [ ] JavaDoc
 - [ ] Prerequisites
 - [ ] Software Requirements
 - [ ] Database Setup
 - [ ] Project Setup
 - [ ] Java Project Creation
 - [ ] Library Dependencies
 - [ ] Database
 - [ ] Entity-Relationship Diagram (ERD)
 - [ ] Database Tables
 - [ ] Modules
     - [ ] User Module
     - [ ] Project Task Module
     - [ ] Milestone Module
 - [ ] Validations
 - [ ] User Validations
 - [ ] Project Task Validations
 - [ ] Milestone Validations
 - [ ] Testing
 - [ ] Unit Testing
 - [ ] Exception Handling
 - [ ] Common Error Messages
 - [ ] Future Improvements
 - [ ] Planned Features
 - [ ] Roadmap
 - [ ] Resources
 - [ ] External Libraries
 - [ ] References
