### ISSUE TITLE
User Module | List User Feature

### ISSUE THREAD

**Issue by JAYAPRAKASHJAISANKAR** [fssa-batch3/jayaprakash.jaisankar__corejava_project_2#13]
### User Story  
As a user, I should be able to log into the application using a valid email and password. If the email or password is incorrect, the application will display an error message indicating that the login credentials are invalid. Specifically, if the email is invalid, the error message will be "Invalid email address." If the email is valid but the password is incorrect, the error message will be "Invalid password."    

### Task
 - [ ] Implement Data Access Object (DAO) Layer.
 - [ ] Implement Service Layer.
 - [ ] Create JUnit Test Cases.
 - [ ] Ensure that the tests cases are passing.
 - [ ] Write clear and concise comments in the code to explain complex logic.
### DAO
- [ ] getAllUsers()
- [ ] Service
- [ ] listAllUser()
- [ ] Junit Test
- [ ] testGetAllUsers()
### Estimation
1 hour

### Flow Chart:
```  mermaid
graph TD
A[[Start]] --> B([TodoMaster Accesses User List])
B --> C[(Retrieve List of User from Database)]
C --> |No User Found| F{{ServiceException}}
C --> |List of User Found| I([Login Successful])
F --> G([Failed to Retrieve User List])
G --> H[[End]]
I --> H


style I fill:#dfd,stroke:#333
style G fill:#fdd,stroke:#333


   ```
