### ISSUE TITLE
User Module | Update User Feature

### ISSUE THREAD

**Issue by JAYAPRAKASHJAISANKAR** [fssa-batch3/jayaprakash.jaisankar__corejava_project_2#14]
### User Story
As a user, I want the ability to edit my profile information in the application. This will allow me to update details like my name, profile image, mobile number, gender, and date of birth. After making these changes, I expect to see my updated information displayed correctly.

### Task
- [ ] Implement Data Access Object (DAO) Layer.
- [ ] Implement Service Layer.
 - [ ] Create JUnit Test Cases.
 - [ ] Ensure that the tests cases are passing.
 - [ ] Write clear and concise comments in the code to explain complex logic.
### DAO
- [ ] updateUser()
- [ ] Service
- [ ] editUser()
### Junit Test
- [ ] testValidUpdateUser()
- [ ] testInvalidUpdateUser()
### Estimation
2 hours

### Flow Chart:
```  mermaid
graph TD
A[[Start]] --> B([User Initiates Update ProjectTask])
B --> C[(Search ProjectTask to Update)]
C --> |ProjectTask Not Found| D{{Service Exception}}
D --> |Fail| E([Failed to Update ProjectTask])
C --> |ProjectTask Found| G([Update ProjectTask Details])
G --> |Save Changes| F([ProjectTask Updated Successfully!])
E --> I[[End]]
F --> |Returns ProjectTask| I

style F fill:#dfd,stroke:#333
style E fill:#fdd,stroke:#333




   ```
