### ISSUE TITLE
Milestone Module | Milestone Create Feature

### ISSUE THREAD

**Issue by JAYAPRAKASHJAISANKAR** [fssa-batch3/jayaprakash.jaisankar__corejava_project_2#16]
Milestone Create Process
User Story
As a  user, I want to be able to create the sub milestone in the project task. When I find a the task  I want to read, I should be able to create a milestone. 
Task
- [ ] Implement Data Access Object (DAO) Layer.
- [ ] Implement Service Layer.
- [ ] Create JUnit Test Cases.
- [ ] Ensure that the tests cases are passing.
- [ ] Write clear and concise comments in the code to explain complex logic.
### DAO
- [ ] todoID
- [ ] task_text
- [ ] task_date
- [ ] task_time
- [ ] is_remainder
### Service
- [ ] todoID
- [ ] task_text
- [ ] task_date
- [ ] task_time
- [ ] is_remainder
### Junit Test
- [ ] testtodoID
- [ ] testtask_text
- [ ] testtask_date
- [ ] testtask_time
- [ ] test is_remainder
### Estimation
3 hours

### Flow Chart:

```  mermaid
graph TD
A[[Start]] --> |Milestone Creation| B([Validate Milestone])
B --> |Valid| C([Search Existing Milestone])
B --> |Invalid| E{{Validation Exception}}
C --> |Milestone Found| F{{Service Exception}}
C --> |Milestone Not Found| D([Add Milestone])
D --> |Success| I([Milestone Added Successfully])
E --> |Fail| G([Failed to Add Milestone])
F --> |Fail| G
G --> H[[End]]
I --> H

style I fill:#dfd,stroke:#333
style G fill:#fdd,stroke:#333

   ```
