### ISSUE TITLE
Milestone | Read

### ISSUE THREAD

**Issue by JAYAPRAKASHJAISANKAR** [fssa-batch3/jayaprakash.jaisankar__corejava_project_2#17]
### User Story
As a user, I want to be able to view a list of all the all milestone from the milestone's collection. The system should provide me with a list that all details. This way, I can easily monitor and manage the milestone.

### Task
 - [ ] Implement Data Access Object (DAO) Layer.
 - [ ] Implement Service Layer.
 - [ ] Create JUnit Test Cases.
 - [ ] Ensure that the tests cases are passing.
- [ ] Write clear and concise comments in the code to explain complex logic.
### DAO
 - [ ] getAllmilestone()
### Service
 - [ ] getAllmilestone()
### Junit Test
 - [ ] testGetAllmilestone()
### Estimation
1 hour

### Flow Chart:
```  mermaid
graph TD
A[[Start]] --> B(User Initiates List of Milestone)
B --> C[(Fetch List of Milestone)]
C --> |Milestone Available| D([Display List of Milestone])
C --> |No Milestone Found| E{{Service Exception}}
E --> G([Failed to get Milestone List])
D --> F[[End]]
G --> F


style D fill:#dfd,stroke:#333
style G fill:#fdd,stroke:#333





   ```
