### ISSUE TITLE
Milestone | Update

### ISSUE THREAD

**Issue by JAYAPRAKASHJAISANKAR** [fssa-batch3/jayaprakash.jaisankar__corejava_project_2#18]
### User Story
As a user, I want to be able to update information about milestone in the milestone's collection. This includes updating details such as
all attribute.

### Task
- [ ] Implement Data Access Object (DAO) Layer.
- [ ] Implement Service Layer.
- [ ] Create JUnit Test Cases.
- [ ] Ensure that the tests cases are passing.
- [ ] Write clear and concise comments in the code to explain complex logic.
### DAO
- [ ] updatemilestone()
- [ ] Service
### Junit Test
 - [ ] testValidUpdatemilestone()
 - [ ] testInvalid updatemilestone()
### Estimation
3 hours

### Flow Chart:
```  mermaid
graph TD
A[[Start]] --> B([User Initiates Update Milestone])
B --> C[(Search Milestone to Update)]
C --> |Milestone Not Found| D{{Service Exception}}
D --> |Fail| E([Failed to Update Milestone])
C --> |Milestone Found| G([Update Milestone Details])
G --> |Save Changes| F([Milestone Updated Successfully!])
E --> I[[End]]
F --> |Returns Milestone| I

style F fill:#dfd,stroke:#333
style E fill:#fdd,stroke:#333



   ```
