### ISSUE TITLE
User Module | Register User 

### ISSUE THREAD

**Issue by JAYAPRAKASHJAISANKAR** [fssa-batch3/jayaprakash.jaisankar__corejava_project_2#5]
### User Story
As a user, I should be able to log into the application using a valid email and password. If the email or password is incorrect, the application will display an error message indicating that the login credentials are invalid. Specifically, if the email is invalid, the error message will be "Invalid email address." If the email is valid but the password is incorrect, the error message will be "Invalid password."

### Task
- [ ] Implement Data Access Object (DAO) Layer.
- [ ] Implement Service Layer.
- [ ] Create JUnit Test Cases.
- [ ] Ensure that the tests cases are passing.
- [ ] Write clear and concise comments in the code to explain complex logic.
### DAO
- [ ] createUser()
- [ ] Service
- [ ] registerUser()
### Junit Test
- [ ] testValidRegisterUser()
- [ ] testInvalidRegisterUser()
### Estimation
3 hours

### Flow:
```  mermaid
graph TD
A[(Start)] --> B([Validate User])
B --> |Valid| C([Check Existing Active User])
B --> |Invalid| E{{Validation Exception}}
C --> |Active User Found| F{{ServiceException}}
C --> |User Not Found| D([Create User])
D --> |Success| I([Registration Successful])
E --> |Fail| G([Registration Failed])
F --> |Fail| G
G --> H[(End)]
I --> H


style I fill:#dfd,stroke:#333
style G fill:#fdd,stroke:#333


   ```
