### ISSUE TITLE
User Module | Login User Feature 

### ISSUE THREAD

**Issue by JAYAPRAKASHJAISANKAR** [fssa-batch3/jayaprakash.jaisankar__corejava_project_2#6]
### User Story
As a user, I want to be able to log into the application using my email and password. If my credentials are correct, I should be granted access to my account. If there's an issue with the credentials, I should receive appropriate error messages.

### Task
 - [ ] Implement Data Access Object (DAO) Layer.
 - [ ] Implement Service Layer.
 - [ ] Create JUnit Test Cases.
 - [ ] Ensure that the tests cases are passing.
 - [ ] Write clear and concise comments in the code to explain complex logic.
### DAO
- [ ] getUser()
- [ ] Service
- [ ] loginUser()
### Junit Test
- [ ] testValidLogin()
- [ ] testInvalidLogin()
### Estimation
3 hours

### Flow Chart

``` mermaid

graph TD
A[[Start]] --> B([Validate User])
B --> |Valid| C[(Retrieve User from Database)]
B --> |Invalid| E{{Validation Exception}}
C --> |User Not Found| F{{ServiceException}}
C --> |User Found| D([Check Password Match])
D --> |Returns User| I([Login Successful])
E --> G([Login Failed])
F --> G
D --> |Password Mismatch| G
G --> H[[End]]
I --> H


style I fill:#dfd,stroke:#333
style G fill:#fdd,stroke:#333




```
